#! /bin/bash
#This is a script designed to do component continous integration
CPPUTEST_URL="https://cpputest.svn.sourceforge.net/svnroot/cpputest/trunk/"
LAST_CHANGE=.cpputest_last_change

function record_date() {
echo `date +%Y%m`>$LAST_CHANGE
}

function do_update() {
  echo "update cpputest per month"
  record_date
  new_rev=`svn up|grep "At revision"`
  new_rev=${new_rev:12}
  org_rev=${org_rev:10}
  if [ $new_rev -eq $org_rev ]; then
    echo "no version change"
  else
    make clean
    make
  fi
}

# update cpputest 
function update_cpputest() {
org_rev=`svn info|grep Revision`
if [ $? -eq 0 ]; then
  #echo "cpputest already checkout, update it"
  cur_date=`date +%Y%m`
  last_update_date=`cat $LAST_CHANGE`
  [ $cur_date -eq $last_update_date ]&&echo "cpputest is up to date"||do_update
else
  #echo "cpputest not checkout yet, checkout it"
  svn co $CPPUTEST_URL .
  record_date
  make
fi

}
update_cpputest


