#! /bin/bash
# This is a script designed to do component continous integration

# add subproject to projects
projects="cpputest backlog-editor sprint"
prj_root=`pwd`
for prj in $projects; do 
  echo "--------runing $prj cci--------"
  if [ -f $prj/component-ci ]; then
    # each sub project should have its own component-ci
    cd $prj
    . `pwd`/component-ci
    cd $prj_root
  else
    echo "component cci not exist in $prj"
  fi
done  


